HOST_WITH_CONTENT_PROBABILITY = 0.5
CACHE_PROBABILITY = 0.5
CACHE_SIZE = 4

LOW_ENERGY_SWITCH_PROB = 0.33
MEDIUM_ENERGY_SWITCH_PROB = 0.33
HIGH_ENERGY_SWITCH_PROB = 0.33

RAND_SWITCH_DENSITY = 0.3

LOW_ENERGY    = 30;
MEDIUM_ENERGY = 40;
HIGH_ENERGY   = 50;
